### ISSUE TITLE
Error Creating a New User

### ISSUE THREAD

**Issue by ZenithClown** [pOrgz/pOrgz-py#1]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
If already a user exists and his database is generated, then adding a new user is creating a problem, however, the JSON object is created.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Initialize a new user `base = pOrgz.pOrgz('user')`
2. Enter Details, and let the system generate Database and JSON File
3. Restart the system and create a new user `base = pOrgz.pOrgz('new-user')`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should be able to create a new use.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
JSON File is updated with the `new user` details but database is not created.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste error detailed traceback )
```python
# Error Traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/pOrgz/pOrgz - Organizer/pOrgz/api/base.py in __init__(self, username)
     76                 with open(self.userfile) as f:
---> 77                     self.session = json.load(f)[self.username]
     78             except (KeyError, FileNotFoundError): # Path Exists, but a New User or First-Run

KeyError: 'new-user'

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-458eea6304e3> in <module>
----> 1 base = pOrgz.pOrgz('new-user') # initializing

~/pOrgz/pOrgz - Organizer/pOrgz/api/base.py in __init__(self, username)
     77                     self.session = json.load(f)[self.username]
     78             except (KeyError, FileNotFoundError): # Path Exists, but a New User or First-Run
---> 79                 self.session = self.userInfo()
     80             except json.JSONDecodeError as err:
     81                 raise InvalidFileFormat(f'Invalid File-Format Found: Please Remove or Correct {self.userfile}')

~/pOrgz/pOrgz - Organizer/pOrgz/api/base.py in userInfo(self)
    154                 json.dump({self.username : values}, f, indent = 4)
    155 
--> 156         return values
    157 
    158     @property

UnboundLocalError: local variable 'values' referenced before assignment
```

[NOTE]: # ( Pick choices based on your environment )
Python Version      : 3.6
Operating System    : Linux
Desktop Environment : Cinnamon

**Comment by pOrgz** [comment]
For better security, and user-handling a new [OAuth REST-API](https://github.com/pOrgz/OAuth-REST-API) is being developed to handle these kind of problems. Also, designing an API keeps the possibility of making a full fledged web-application (online) if required.
